"""
stock_universe.py — Full NSE stock universe

get_symbols("nifty50")    →  50 stocks  (~2 min scan)
get_symbols("nifty100")   → 100 stocks  (~4 min scan)  ← DEFAULT
get_symbols("nifty200")   → 200 stocks  (~8 min scan)
get_symbols("nifty500")   → 500 stocks  (~20 min scan)
"""

NIFTY_50 = [
    "RELIANCE","TCS","HDFCBANK","ICICIBANK","INFY",
    "HINDUNILVR","ITC","SBIN","BHARTIARTL","KOTAKBANK",
    "LT","AXISBANK","BAJFINANCE","ASIANPAINT","MARUTI",
    "TITAN","SUNPHARMA","ULTRACEMCO","WIPRO","NESTLEIND",
    "NTPC","POWERGRID","ONGC","COALINDIA","TATAMOTORS",
    "JSWSTEEL","TATASTEEL","ADANIENT","ADANIPORTS","GRASIM",
    "TECHM","HCLTECH","BAJAJFINSV","BAJAJ-AUTO","EICHERMOT",
    "DIVISLAB","CIPLA","DRREDDY","APOLLOHOSP","BRITANNIA",
    "TATACONSUM","HEROMOTOCO","BPCL","HINDALCO","UPL",
    "INDUSINDBK","SHREECEM","SBILIFE","HDFCLIFE","M&M",
]

NIFTY_NEXT_50 = [
    "ABB","ADANIGREEN","ADANITRANS","AMBUJACEM","AUROPHARMA",
    "BANDHANBNK","BANKBARODA","BERGEPAINT","BIOCON","BOSCHLTD",
    "CHOLAFIN","COLPAL","CONCOR","CUMMINSIND","DABUR",
    "DLF","GAIL","GODREJCP","GODREJPROP","HAVELLS",
    "ICICIGI","ICICIPRULI","IDFCFIRSTB","INDUSTOWER","IRCTC",
    "JINDALSTEL","JUBLFOOD","LICI","LUPIN","MCDOWELL-N",
    "MPHASIS","MOTHERSON","MUTHOOTFIN","NAUKRI","NMDC",
    "OFSS","PAGEIND","PETRONET","PIIND","PNB",
    "PGHH","SAIL","SIEMENS","SRF","TORNTPHARM",
    "TRENT","VEDL","VOLTAS","WHIRLPOOL","ZOMATO",
]

NIFTY_MIDCAP_100 = [
    "ABCAPITAL","ABFRL","APLAPOLLO","APLLTD","ATGL",
    "AUBANK","ATUL","BALKRISIND","BATAINDIA","BAYERCROP",
    "BLUESTARCO","BSOFT","CANBK","CANFINHOME","CARBORUNIV",
    "CASTROLIND","CEATLTD","CENTURYTEX","CHAMBLFERT","CHENNPETRO",
    "COFORGE","CROMPTON","CSBBANK","CUB","CYIENT",
    "DEEPAKNTR","DELTACORP","DELHIVERY","DEVYANI","DIXON",
    "DMART","EDELWEISS","ELGIEQUIP","EMAMILTD","ENDURANCE",
    "EQUITASBNK","EXIDEIND","FACT","FEDERALBNK","FIVESTAR",
    "FORTIS","GLENMARK","GMDCLTD","GNFC","GPPL",
    "GRANULES","GSFC","GUJGASLTD","HAL","HAPPSTMNDS",
    "HFCL","HINDCOPPER","HINDPETRO","HONAUT","IBREALEST",
    "IDFC","IDFCFIRSTB","IFCI","IIFL","INDIACEM",
    "INDIANB","INDIGO","IOC","IPCALAB","IRFC",
    "JCHAC","JKCEMENT","JKLAKSHMI","JMFINANCIL","JSL",
    "JUBLINGREA","JUSTDIAL","KAJARIACER","KALPATPOWR","KANSAINER",
    "KEC","KPITTECH","KPRMILL","KRBL","LALPATHLAB",
    "LAURUSLABS","LICHSGFIN","LINDEINDIA","LTTS","LUXIND",
    "MAHINDCIE","MARICO","MFSL","MIDHANI","MINDTREE",
    "MOTILALOFS","MPWR","NATCOPHARM","NAVINFLUOR","NBCC",
    "NFL","NIITLTD","NLCINDIA","NUVOCO","OBEROIRLTY",
]

NIFTY_SMALLCAP_100 = [
    "AARTIDRUGS","AARTIIND","ACCELYA","ACE","AEGISCHEM",
    "AFFLE","AJANTPHARM","AKZOINDIA","ALKEM","ALLCARGO",
    "AMARAJABAT","AMBER","ANANDRATHI","ANGELONE","APOLLOTYRE",
    "ASTERDM","ASTRAL","AVANTIFEED","AXISCADES","BAJAJCON",
    "BALRAMCHIN","BAYERCROP","BEML","BHARATFORG","BHEL",
    "BIKAJI","BLUEDART","BPCL","BRIGADE","CAMPUS",
    "CAPLIPOINT","CDSL","CENTURYPLY","CERA","CESC",
    "CHALET","CLEAN","CRAFTSMAN","CREDITACC","CSB",
    "DATAPATTNS","DBREALTY","DCB","DEEPAKFERT","DFMFOODS",
    "DHANUKA","DOLLAR","ELECTCAST","EMKAY","EPL",
    "EQUITAS","ERIS","ESABINDIA","ESAFSFB","ESCORTS",
    "ETHOSLTD","FAZE3Q","FEDERALBNK","FIEMIND","FINPIPE",
    "FLAIR","FORCEMOT","FSL","GAEL","GARFIBRES",
    "GESHIP","GICHSGFIN","GMMPFAUDLR","GNFC","GODFRYPHLP",
    "GPPL","GREENLAM","GREENPLY","GRINDWELL","GRSE",
    "GSFC","GULFOILLUB","HAPPYFORGE","HFCL","HINDCOPPER",
    "IFCI","IIFL","INDIACEM","INDIANB","IRFC",
    "JCHAC","JKLAKSHMI","JUBLINGREA","JUSTDIAL","KAJARIACER",
    "KALPATPOWR","KANSAINER","KEC","KPITTECH","KRBL",
    "LALPATHLAB","LAURUSLABS","LICHSGFIN","LINDEINDIA","LUXIND",
]

def get_symbols(universe: str = "nifty100") -> list[str]:
    u = universe.lower()
    if u == "nifty50":
        return NIFTY_50
    elif u == "nifty100":
        return NIFTY_50 + NIFTY_NEXT_50
    elif u == "nifty200":
        return NIFTY_50 + NIFTY_NEXT_50 + NIFTY_MIDCAP_100
    elif u in ("nifty500", "all"):
        return NIFTY_50 + NIFTY_NEXT_50 + NIFTY_MIDCAP_100 + NIFTY_SMALLCAP_100
    elif u == "midcap":
        return NIFTY_MIDCAP_100
    elif u == "smallcap":
        return NIFTY_SMALLCAP_100
    return NIFTY_50 + NIFTY_NEXT_50
